# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI AND CD

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
        

    strategy:
      matrix:
        node-version: [14.17.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - name : Run the Node JS App
      working-directory: ./Backend
      run: |
          npm ci
          npm run build --if-present
          npm test
  deploy:
    
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Build, Push and Deploy to Heroku # set whatever name you want to this step
       id: heroku
       uses: jctaveras/heroku-deploy@v1.0.0 # use the latest version of the action
       with:
         email: ${{secrets.HEROKU_EMAIL }} # your heroku email
         api_key: ${{secrets.HEROKU_API_KEY}} # your heroku api key
         app_name: ${{secrets.HEROKU_APP_NAME}} # you aplication name
         dockerfile_path: './Backend' # set the path to the folder where the Dockerfile is located
         

      
    
